# Data cleaning

Picking out the relevant variables from the transit information datasets

One has information on the routes, and another on the detailed legs for each out. 

## Setting things up

First, let's get our working directories in place and import the necessary libraries:

In [4]:
import numpy as np
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

raw_data = "//Users//afan//Desktop//Misc//HMW_Transit//prep//raw_data//"
cleaned_data  = "//Users//afan//Desktop//Misc//HMW_Transit//cleaned_data//"

## Relevant Variables

Some of these datasets have a ton of columns. Let's just figure out the relevant ones for now. 

I want to look at these two datasets in particular: 
1. metro_routes.csv
2. metro_legs.csv

One at a time

## metro_routes.csv

In [8]:
mr_str = raw_data + "metro_routes.csv"
mr = pd.read_csv(mr_str)
mr.head(0)

Empty DataFrame
Columns: [Unnamed: 0, ItineraryId, Created, Kml, StartTime, EndTime, AdjustedStartTime, AdjustedEndTime, StartStopName, EndStopName, StartStopId, EndStopId, StartAddress, EndAddress, TransferCount, TravelTypes, WalkDistance, RequestId, StartLon, StartLat, EndLon, EndLat, LocalTimeOffset, Legs, school, school_id, length]
Index: []

In [10]:
# From here, I'll make a list of columns to keep 

mr_cols = ['ItineraryId', # needed to link the legs to the itinerary 
            'Created', # for version control reasons
            'AdjustedStartTime', 'AdjustedEndTime', # times
            'TransferCount', 'TravelTypes', 'WalkDistance', 'length', # quality of the trip 
            'school' # of course
            ]

mr_final = mr[mr_cols]
mr_final.head()

,ItineraryId,Created,AdjustedStartTime,AdjustedEndTime,TransferCount,TravelTypes,WalkDistance,length,school
0,2657431e-4da1-48fc-9d0f-5ff53d67899d,2021-11-19T22:35:21.6716211Z,2021-11-19 23:12:29+00:00,2021-11-20 01:14:48+00:00,2,"Walk,Bus",1.247141,0 days 02:02:19,GRISSOM EL
1,98b398ba-56e0-49e1-abf1-4ccb398420ab,2021-11-19T22:35:21.6720636Z,2021-11-19 23:12:29+00:00,2021-11-20 01:22:32+00:00,2,"Walk,Bus",1.629523,0 days 02:10:03,GRISSOM EL
2,fdffeee8-ee24-432a-966a-d2099559239b,2021-11-19T22:35:21.672286Z,2021-11-19 22:42:29+00:00,2021-11-20 01:33:18+00:00,3,"Walk,Bus",1.001308,0 days 02:50:49,GRISSOM EL
3,5f023cde-d267-4972-a8d7-24790914cb52,2021-11-19T22:35:32.5344502Z,2021-11-19 22:44:19+00:00,2021-11-20 00:21:45+00:00,3,"Walk,Bus",0.268066,0 days 01:37:26,KING EARLY CHILDHOOD CTR
4,a1ae727a-4d62-4e8a-a32e-f6ac3b36a906,2021-11-19T22:35:32.5349315Z,2021-11-19 22:53:27+00:00,2021-11-20 00:59:31+00:00,3,"Walk,Bus",0.742854,0 days 02:06:04,KING EARLY CHILDHOOD CTR

## metro_legs.csv

In [6]:
ml_str = raw_data + "metro_legs.csv"
ml = pd.read_csv(ml_str)
ml.head(5)

,Unnamed: 0,0,Address,AdjustedStartTime,AgencyAbbreviation,AgencyName,Created,DataSource,DelayFromScheduleInSeconds,DirectionId,DirectionName,DirectionVariantId,Duration,ItineraryId,ItineraryLegId,Lat,Length,Lon,Ordinal,RouteDestinationName,RouteId,RouteName,ShapeUri,StartTime,StopId,StopName,TransportType,TripHeadsign,TripId
0,0,NaN,NaN,2022-01-07T20:09:37Z,NaN,NaN,2022-01-07T19:54:59.2862139Z,NaN,NaN,NaN,NaN,NaN,706.0,2a8f39ac-77ef-4c78-becd-d9e26f56ab1e,393966447.0,29.666614,0.608493,-95.329629,0.0,NaN,NaN,NaN,NaN,2022-01-07T20:09:37Z,NaN,NaN,Walk,NaN,NaN
1,1,NaN,NaN,2022-01-07T20:22:23Z,RideMetro,Houston,2022-01-07T19:54:59.2862395Z,NaN,0.0,Ho414_4620_41946_0,KASHMERE TC,Ho414_4620_41946_0_0,2857.0,2a8f39ac-77ef-4c78-becd-d9e26f56ab1e,393966448.0,29.667021,10.178859,-95.337059,1.0,KASHMERE TC,Ho414_4620_41946,80.0,NaN,2022-01-07T20:22:23Z,Ho414_4620_3462,M L King Blvd @ Bellfort,Bus,KASHMERE TC,Ho414_4620_9273380
2,2,NaN,NaN,2022-01-07T21:13:42Z,NaN,NaN,2022-01-07T19:54:59.2862421Z,NaN,NaN,NaN,NaN,NaN,18.0,2a8f39ac-77ef-4c78-becd-d9e26f56ab1e,393966449.0,29.814120,0.015882,-95.327876,2.0,NaN,NaN,NaN,NaN,2022-01-07T21:13:42Z,Ho414_4620_76,Kashmere Transit Center,Walk,NaN,NaN
3,3,NaN,NaN,2022-01-07T21:15:00Z,RideMetro,Houston,2022-01-07T19:54:59.2862811Z,NaN,0.0,Ho414_4620_41906_1,MEMORIAL CITY,Ho414_4620_41906_1_0,2020.0,2a8f39ac-77ef-4c78-becd-d9e26f56ab1e,393966450.0,29.814277,7.602031,-95.327946,3.0,MEMORIAL CITY,Ho414_4620_41906,26.0,NaN,2022-01-07T21:15:00Z,Ho414_4620_76_D,KASHMERE TRANSIT CENTER BAY D,Bus,MEMORIAL CITY,Ho414_4620_9262824
4,4,NaN,NaN,2022-01-07T21:49:40Z,NaN,NaN,2022-01-07T19:54:59.2862815Z,NaN,NaN,NaN,NaN,NaN,125.0,2a8f39ac-77ef-4c78-becd-d9e26f56ab1e,393966451.0,29.801630,0.108456,-95.454342,4.0,NaN,NaN,NaN,NaN,2022-01-07T21:49:40Z,Ho414_4620_12077,W 18Th St @ Northwest Fwy,Walk,NaN,NaN

In [7]:
ml.DelayFromScheduleInSeconds.describe()

count    3329.000000
mean       61.896065
std       190.148237
min      -534.000000
25%         0.000000
50%         0.000000
75%         0.000000
max      2380.000000
Name: DelayFromScheduleInSeconds, dtype: float64

In [5]:
ml_cols = ['ItineraryId', # linking purposes
            'AdjustedStartTime', 'DelayFromScheduleInSeconds', 'Duration', # quality of trip 
            'Lat', 'Length', 'Lon', # location 
            'Ordinal', 	#  PICK BACK UP HERE
            'RouteDestinationName',
            'RouteName', 'StartTime', 
            'StopName', 'TransportType'
]

ml_final = ml[ml_cols]
ml_final.head()

,ItineraryId,AdjustedStartTime,DelayFromScheduleInSeconds,Duration,Lat,Length,Lon,Ordinal,RouteDestinationName,RouteName,StartTime,StopName,TransportType
0,2a8f39ac-77ef-4c78-becd-d9e26f56ab1e,2022-01-07T20:09:37Z,NaN,706.0,29.666614,0.608493,-95.329629,0.0,NaN,NaN,2022-01-07T20:09:37Z,NaN,Walk
1,2a8f39ac-77ef-4c78-becd-d9e26f56ab1e,2022-01-07T20:22:23Z,0.0,2857.0,29.667021,10.178859,-95.337059,1.0,KASHMERE TC,80.0,2022-01-07T20:22:23Z,M L King Blvd @ Bellfort,Bus
2,2a8f39ac-77ef-4c78-becd-d9e26f56ab1e,2022-01-07T21:13:42Z,NaN,18.0,29.814120,0.015882,-95.327876,2.0,NaN,NaN,2022-01-07T21:13:42Z,Kashmere Transit Center,Walk
3,2a8f39ac-77ef-4c78-becd-d9e26f56ab1e,2022-01-07T21:15:00Z,0.0,2020.0,29.814277,7.602031,-95.327946,3.0,MEMORIAL CITY,26.0,2022-01-07T21:15:00Z,KASHMERE TRANSIT CENTER BAY D,Bus
4,2a8f39ac-77ef-4c78-becd-d9e26f56ab1e,2022-01-07T21:49:40Z,NaN,125.0,29.801630,0.108456,-95.454342,4.0,NaN,NaN,2022-01-07T21:49:40Z,W 18Th St @ Northwest Fwy,Walk